### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by fuhua666** [xinyunaha/icveHelper#5]
Traceback (most recent call last):
  File "C:/Users/21742/Desktop/8989.py", line 229, in <module>
    Mooc()
  File "C:/Users/21742/Desktop/8989.py", line 37, in __init__
    self.Run()
  File "C:/Users/21742/Desktop/8989.py", line 128, in Run
    self.view(id, False)
  File "C:/Users/21742/Desktop/8989.py", line 153, in view
    print('\t {} 等待 {}s 后继续'.format(res['msg'], sleepTime))
KeyError: 'msg'
上面是运行错误显示的东西，那个你还在维护吗？

**Comment by EastItem** [comment]
已在[分支](https://github.com/EastItem/icveHelper)中修复。觉得好用不妨点个star
